"""Summary of changes 2

Revision ID: 2551e9db7486
Revises: 1bdceb555988
Create Date: 2025-12-07 22:09:39.510582

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2551e9db7486'
down_revision: Union[str, Sequence[str], None] = '1bdceb555988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_lines', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('order_lines', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_order_lines_item_id'), 'order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_foreign_key(None, 'order_lines', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'order_lines', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_lines', type_='foreignkey')
    op.drop_constraint(None, 'order_lines', type_='foreignkey')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_item_id'), table_name='order_lines')
    op.drop_column('order_lines', 'item_id')
    op.drop_column('order_lines', 'order_id')
    # ### end Alembic commands ###
