"""1

Revision ID: 3a4166d2760c
Revises: c10064056806
Create Date: 2026-01-18 09:04:17.786427

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a4166d2760c'
down_revision: Union[str, Sequence[str], None] = 'c10064056806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_order_lines_item_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_column('items', 'discount')
    op.drop_column('items', 'is_active')
    op.drop_column('items', 'available')
    op.drop_column('items', 'uom')
    op.add_column('orders', sa.Column('table_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    op.create_index(op.f('ix_orders_item_id'), 'orders', ['item_id'], unique=False)
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'tables', ['table_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'items', ['item_id'], ['id'])
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'closed_at')
    op.drop_column('orders', 'client')
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('table', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('client', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_item_id'), table_name='orders')
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'item_id')
    op.drop_column('orders', 'table_id')
    op.add_column('items', sa.Column('uom', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('available', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_table('order_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('uom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('final_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('order_lines_item_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_lines_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_lines_pkey'))
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_lines_item_id'), 'order_lines', ['item_id'], unique=False)
    op.drop_table('tables')
    # ### end Alembic commands ###
