"""add_role_category_is_available_updated_at

Revision ID: 5d91df8b2a77
Revises: 3a4166d2760c
Create Date: 2026-04-12 23:31:54.024606

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d91df8b2a77'
down_revision: Union[str, Sequence[str], None] = '3a4166d2760c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('items', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.add_column('items', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=40),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.alter_column('items', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'is_available')
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
