"""add_stock_qty_to_items

Revision ID: 64f91199daa5
Revises: 5d91df8b2a77
Create Date: 2026-04-13 23:46:37.996804

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f91199daa5'
down_revision: Union[str, Sequence[str], None] = '5d91df8b2a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('stock_qty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stock_qty')
    # ### end Alembic commands ###
